global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "llmops_fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["llmops_app:8001"]  # container name + internal port

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
