# Dockerfile.evidently
FROM python:3.10

# Set a working directory
WORKDIR /app

# System dependencies needed for pandas, numpy, evidently, boto3
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    libssl-dev \
    python3-dev \
    curl \
 && rm -rf /var/lib/apt/lists/*

# Copy Evidently requirements
COPY src/requirements-evidently.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --upgrade pip --default-timeout=120
RUN pip install --no-cache-dir -r requirements.txt --default-timeout=120

# Copy Evidently app files
COPY src/monitoring/evidently_app.py /app/monitoring/evidently_app.py
COPY src/monitoring/generate_drift.py /app/monitoring/generate_drift.py


# Copy only monitoring/evidently code
COPY src/monitoring /app/monitoring


# Create directory for generated reports
RUN mkdir -p /app/monitoring

# Copy reference dataset from ROOT-LEVEL /data/
COPY data/raw/amazon.csv /app/data/raw/amazon.csv

# Expose Evidently FastAPI port
EXPOSE 7000

# Start Evidently dashboard server
CMD ["uvicorn", "monitoring.evidently_app:app", "--host", "0.0.0.0", "--port", "7000"]
