repos:
  # Basic hygiene hooks (official pre-commit hooks)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files  # blocks huge files by mistake

  # Python security: secret scanning (Yelp's detect-secrets)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        # Create baseline once (see below), then keep it updated in PRs.

  # Python formatter: Black (opinionated, stable)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  # Python linter: Ruff (very fast; includes many flake8 rules, isort, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]  # auto-fix where possible
        language_version: python3.11
