minimum_pre_commit_version: "3.5.0"

default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]