{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "rate(recommendations_total[5m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\"rate(recommendations_total[5m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recommendations_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    { "expr": "recommendations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rate(recommendation_duration_seconds_sum[5m]) / rate(recommendation_duration_seconds_count[5m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{\"increase(recommendation_duration_seconds_sum[5m]) / increase(recommendation_duration_seconds_count[5m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "empty_recommendations_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "empty_recommendations_total", "legendFormat": "__auto" }
   ]
  }
 ]
}